eAcademy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eAcademyApp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eAcademyApp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

app_name = 'eAcademyApp'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/register/', views.register_view, name='register'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('courses/', views.course_list, name='course_list'),
    path('courses/create/', views.create_course, name='create_course'),
    path('membership/', views.membership_view, name='membership'),
    path('membership/upgrade/<str:membership_type>/', views.upgrade_view, name='upgrade'),
    path('membership/upgrade/<str:membership_type>/currency/', views.currency_selection, name='currency_selection'),
    path('membership/upgrade/<str:membership_type>/payment/<str:currency>/', views.payment_view, name='payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('my_courses/', views.student_courses, name='student_courses'),
    path('payment/', views.payment_view, name='payment'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('contact/', views.contact, name='contact'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('student-management/', views.student_management, name='student_management'),
    path('upgrade/<str:membership_type>/', views.upgrade_view, name='upgrade'),
    path('course_files/<path:file_name>/', views.serve_course_file, name='serve_course_file'),
    path('add_to_cart/<int:course_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:course_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('enrollment/', views.enrollment, name='enrollment'),
    path('instructor-requests/', views.instructor_requests_view, name='instructor_requests'),
    path('accept-instructor-request/<int:user_id>/', views.accept_instructor_request_view, name='accept_instructor_request'),
    path('reject-instructor-request/<int:user_id>/', views.reject_instructor_request_view, name='reject_instructor_request'),
    # URL pattern for the forgot password feature
    path('accounts/forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('upload-content/', views.upload_content, name='upload_content'),

    # URL patterns for the built-in Django password reset views
    path('accounts/reset-password/', auth_views.PasswordResetView.as_view(
        template_name='reset_password.html',
        email_template_name='reset_password_email.html',
        success_url='/accounts/reset-password/done/'
    ), name='password_reset'),


    path('confirm-code/', views.confirm_code_view, name='confirm_code'),
    path('reset-password/', views.reset_password_view, name='reset_password'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eAcademyApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver


class Course(models.Model):
    LEVEL_CHOICES = [
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    ]
    title = models.CharField(max_length=200)
    description = models.TextField()
    level_type = models.CharField(max_length=12, choices=LEVEL_CHOICES, default='beginner')
    instructor = models.ForeignKey(User, on_delete=models.CASCADE)
    files = models.FileField(upload_to='course_files/')
    image = models.ImageField(upload_to='course_images/', blank=True, null=True, default='default.jpg')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            # Resize the uploaded image to a smaller size for better performance
            img = Image.open(self.image.path)

            max_size = (300, 300)
            if img.height > max_size[0] or img.width > max_size[1]:
                img.thumbnail(max_size)
                img.save(self.image.path)


class WeeklyContent(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    week_number = models.PositiveIntegerField()
    title = models.CharField(max_length=200)
    description = models.TextField()
    content_file = models.FileField(upload_to='weekly_content/')
    assignment_file = models.FileField(upload_to='weekly_content/assignment/', default='Lec_2_-_Python_Programming_L3gQPaa.pdf')
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    max_grade = models.DecimalField(max_digits=5, decimal_places=2, default=100.0)

    def __str__(self):
        return f"{self.course.title} - Week {self.week_number}: {self.title}"


class Membership(models.Model):
    MEMBERSHIP_CHOICES = [
        ('gold', 'Gold'),
        ('silver', 'Silver'),
        ('bronze', 'Bronze'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    membership_type = models.CharField(max_length=10, choices=MEMBERSHIP_CHOICES, default='bronze')

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    CURRENCY_CHOICES = [
        ('USD', 'USD'),
        ('EUR', 'EUR'),
        ('GBP', 'GBP'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES)
    payment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.amount} {self.currency}"


class UserProfile(models.Model):
    USER_TYPE_CHOICES = [
        ('student', 'Student'),
        ('professor', 'Professor'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, default='student')
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    email = models.EmailField(unique=True, null=True)

    def __str__(self):
        return self.user.username

    def isteacher(self):
        return self.user_type == 'professor'

    def isstudent(self):
        return self.user_type == 'student'

class CartItem(models.Model):
    student = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.student.user.username} - {self.course.title}"


class InstructorRequest(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)

    def __str__(self):
        return f"Instructor Request - {self.user.username}"


class Enrollment(models.Model):
    student = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    enrollment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.student.user.username} - {self.course.title}"


class StudentCourse(models.Model):
    student = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.student.user.username} - {self.course.title}"

class StudentAssignment(models.Model):
    student = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    weekly_content = models.ForeignKey(WeeklyContent, on_delete=models.CASCADE)
    assignment_answer_file = models.FileField(upload_to='student_assignment_answers/', blank=True, null=True)
    grade = models.DecimalField(max_digits=5, decimal_places=2, default=0.0)
    attendance = models.PositiveIntegerField(default=0)

    def get_assignment_file_url(self):
        if self.assignment_answer_file:
            return self.assignment_answer_file.url
        return None
    def __str__(self):
        return f"{self.student.user.username} - Week {self.weekly_content.week_number}: {self.weekly_content.title}"

templates/ConfirmCode.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h1 class="mb-0 text-center">Enter Confirmation Code</h1>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="confirmation_code">Confirmation Code:</label>
                                <input type="text" class="form-control" id="confirmation_code" name="confirmation_code" required>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ForgotPassword.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h1 class="mb-0 text-center">Forgot Password</h1>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="email">Email:</label>
                                <input type="email" class="form-control" id="email" name="email" required>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Send Confirmation Code</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Online Learning Website</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'eAcademyApp/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">eAcademy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">

            <!-- Left Section -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item {% if request.path == '/courses/' %}active{% endif %}">
                    <a class="nav-link" href="/courses/">Courses</a>
                </li>
            <!-- Show "My Courses" link for authenticated student users -->
                {% if request.user.is_authenticated and request.user.userprofile.isstudent %}
                    <li class="nav-item {% if request.path == '/student_courses/' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'eAcademyApp:student_courses' %}">My Courses</a>
                    </li>
                {% endif %}
                <!-- Show/Hide membership section -->
                {% if request.user.is_authenticated and request.user.userprofile.isstudent %}
                    <li class="nav-item {% if request.path == '/membership/' %}active{% endif %}">
                        <a class="nav-link" href="/membership/">Membership</a>
                    </li>
                {% endif %}

                 <!-- My Grades link for student users -->
                {% if request.user.userprofile.isstudent %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'eAcademyApp:dashboard' %}">Dashboard</a>
                    </li>
                {% endif %}

                <!-- Show/Hide student management section -->
                {% if request.user.is_authenticated and request.user.userprofile.isteacher %}
                    <li class="nav-item {% if request.path == '/upload-content/' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'eAcademyApp:upload_content' %}">Course Builder</a>
                    </li>
                    <li class="nav-item {% if request.path == '/student-management/' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'eAcademyApp:student_management' %}">Student Management</a>
                    </li>
                {% endif %}

                <li class="nav-item {% if request.path == '/contact/' %}active{% endif %}">
                    <a class="nav-link" href="/contact/">Contact</a>
                </li>
                <li class="nav-item {% if request.path == '/aboutus/' %}active{% endif %}">
                    <a class="nav-link" href="/aboutus/">About Us</a>
                </li>

            </ul>

            <!-- Right Section -->
            <ul class="navbar-nav">
                <!-- Cart Button -->
                {% if request.user.is_authenticated and request.user.userprofile.isstudent %}
                    <li class="nav-item {% if request.path == '/cart/' %}active{% endif %}">
                        <a class="nav-link" href="/cart/">
                            <div class="cart-icon"></div>
                        </a>
                    </li>
                {% endif %}
            </ul>

            <ul class="navbar-nav">
                <!-- Display login and logout buttons -->
                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                        <li class="nav-item {% if request.path == '/instructor-requests/' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'eAcademyApp:instructor_requests' %}">Instructor Requests</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/logout/">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item {% if request.path == '/accounts/login/' %}active{% endif %}">
                        <a class="nav-link" href="/accounts/login/">Login</a>
                    </li>
                    <li class="nav-item {% if request.path == '/accounts/register/' %}active{% endif %}">
                        <a class="nav-link" href="/accounts/register/">Register</a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </nav>

    <!-- Display messages -->
    {% if messages %}
        <div class="container mt-3">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% block content %}
    {% endblock %}

<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/checkout.html
<!-- checkout.html -->
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-header">
                <h2 class="mb-0">Course Enrollment Summary</h2>
            </div>
            <div class="card-body">
                <p class="card-text">Hello, {{ user_profile.user.username }}!</p>
                <p class="card-text">You are currently a <strong>{{ user_membership.membership_type }}</strong> member, eligible to register <strong>{{ max_registrations }}</strong> courses of level: <strong>{{ access_levels|join:", " }}</strong></p>
                <p class="card-text">You have {{ previous_registrations }} courses already registered.</p>
                <p class="card-text">You have {{ cart_courses.count }} course registration(s) in your cart.</p>

                {% if cart_valid == 0 %}
                    <p class="card-text">You are eligible to register for the following courses:</p>
                    <ul class="list-group">
                        {% for course in cart_courses %}
                                <li class="list-group-item">{{ course.course.title }} ({{ course.course.level_type.capitalize }})</li>
                        {% endfor %}
                    </ul>
                    <div class="text-center mt-3">
                        <form method="post" action="{% url 'eAcademyApp:enrollment' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success">Enroll in Courses</button>
                        </form>
                    </div>
                {% else %}
                    {% if cart_valid == 1 %}
                        <p class="card-text">Please remove some courses from your cart or upgrade your membership tier.</p>
                    {% elif cart_valid == 2 %}
                        <p class="card-text">Please remove the course(s) with a higher level or consider upgrading your membership tier.</p>
                        <ul class="list-group">
                        {% for course in cart_courses %}
                                {% if course.course.level_type not in access_levels %}
                                    <li class="list-group-item">{{ course.course.title }} ({{ course.course.level_type.capitalize }})</li>
                                {% endif %}
                        {% endfor %}
                        </ul>
                    {% elif cart_valid == 3 %}
                        <p class="card-text">Please remove some courses from your cart or upgrade your membership tier.</p>
                        <p class="card-text">Please remove the course(s) with a higher level or consider upgrading your membership tier.</p>
                        <ul class="list-group">
                        {% for course in cart_courses %}
                                {% if course.course.level_type not in access_levels %}
                                    <li class="list-group-item">{{ course.course.title }} ({{ course.course.level_type.capitalize }})</li>
                                {% endif %}
                        {% endfor %}
                        </ul>
                    {% endif %}
                    <div class="text-center mt-3">
                        <a href="{% url 'eAcademyApp:cart' %}" class="btn btn-secondary">Go back to cart</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/course.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">

   <form method="GET" class="form-inline justify-content-center mb-4">
    <div class="form-row align-items-center">
        <div class="col-md-4 mt-2 mt-md-0">
            <label class="sr-only" for="level-filter">Level Filter</label>
            <select name="level" id="level-filter" class="form-control">
                <option value="">All Levels</option>
                {% for choice in level_choices %}
                    <option value="{{ choice.0 }}" {% if level_filter == choice.0 %}selected{% endif %}>{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>
            <div class="col-md-5">
            <label class="sr-only" for="search-input">Search Courses</label>
            <div class="input-group">
                <input type="text" name="q" id="search-input" class="form-control" placeholder="Search courses...">
                <div class="input-group-append">
                    <button type="submit" class="btn btn-primary">Filter</button>
                </div>
            </div>
        </div>

        <div class="col-md-3 mt-2 mt-md-0">
            <a href="{% url 'eAcademyApp:course_list' %}" class="btn btn-block btn-secondary">Clear Filters</a>
        </div>
    </div>
</form>

        <div class="card">
            <div class="card-header">
                <h2 class="mb-0 text-center">Explore our Extensive Course Catalog!</h2>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6 mx-auto text-center">
                        {% if user.is_authenticated and user.userprofile.isteacher %}
                            <a href="/courses/create/" class="btn btn-success mt-3 mb-3">Create New Course</a>
                        {% endif %}
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="course-list">
                            {% for course in courses %}
                                <div class="card mb-3">
                                    <div class="card-body">
                                        {% if course.is_registered %}
                                            <div class="alert alert-info" role="alert">
                                                You are already registered in this course!
                                            </div>
                                        {% endif %}
                                        <h5 class="card-title"><strong>{{ course.title }}</strong></h5>
                                        <p class="card-text">{{ course.description }}</p>
                                        <p class="card-text"><strong>Course Level:</strong> {{ course.level_type.capitalize }}</p>
                                        <p class="card-text"><strong>Instructor:</strong> {{ course.instructor.first_name }} {{ course.instructor.last_name }}</p>
                                        <div class="course-image">
                                            <img src="{{ course.image.url }}" alt="{{ course.title }}" class="img-fluid">
                                        </div>
                                        <br>
                                        <a href="{{ course.files.url }}" class="btn btn-primary">Download Course Outline</a>
                                        {% if user.is_authenticated and user.userprofile.isstudent %}
                                            <div class="d-flex mt-3">
                                                {% if course.is_in_cart %}
                                                    <form method="post" action="{% url 'eAcademyApp:remove_from_cart' course.id %}">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-sm btn-danger">Remove from Cart</button>
                                                    </form>
                                                {% elif not course.is_registered %}
                                                    <form method="post" action="{% url 'eAcademyApp:add_to_cart' course.id %}">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-sm btn-success">Add to Cart</button>
                                                    </form>
                                                {% endif %}
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                                <!-- Add some space between course entries -->
                                <div class="mt-4"></div>
                            {% empty %}
                                <div class="alert alert-info mt-3" role="alert">
                                    No courses available.
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/instructor_requests.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Instructor Requests</h2>
                </div>
                <div class="card-body">
                    {% if instructor_requests %}
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="text-center align-middle">Username</th>
                                    <th class="text-center align-middle">Status</th>
                                    <th class="text-center align-middle">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for request in instructor_requests %}
                                    <tr>
                                        <td class="text-center align-middle">
                                            {% if request.is_approved %}
                                                {{ request.user.username }} <span class="text-success">&#10004;</span>
                                            {% else %}
                                                {{ request.user.username }}
                                            {% endif %}
                                        </td>
                                        <td class="text-center align-middle">
                                            {% if request.is_approved %}
                                                <span class="text-success">Approved</span>
                                            {% elif request.is_rejected %}
                                                <span class="text-danger">Rejected</span>
                                            {% else %}
                                                <span class="text-warning">Pending</span>
                                            {% endif %}
                                        </td>
                                        <td class="text-center align-middle">
                                            {% if not request.is_approved and not request.is_rejected %}
                                                <form class="d-inline-block mr-2" method="post" action="{% url 'eAcademyApp:accept_instructor_request' request.user.id %}">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-success">Accept</button>
                                                </form>
                                                <form class="d-inline-block" method="post" action="{% url 'eAcademyApp:reject_instructor_request' request.user.id %}">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-danger">Reject</button>
                                                </form>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <p class="text-center">No instructor requests found.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h2 class="mb-0 text-center">Welcome Back! Please Log In.</h2>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username">Username:</label>
                                <input type="text" class="form-control" id="username" name="username" required>
                            </div>
                            <div class="form-group">
                                <label for="password">Password:</label>
                                <input type="password" class="form-control" id="password" name="password" required>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Login</button>
                                <a href="{% url 'eAcademyApp:forgot_password' %}" class="btn btn-link">Forgot Password ?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}